// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DownloadArea: typeof import('./src/components/DownloadArea.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    FooterArea: typeof import('./src/components/FooterArea.vue')['default']
    MainContent: typeof import('./src/components/MainContent.vue')['default']
    MoreInfo: typeof import('./src/components/MoreInfo.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
  }
}
